#!/bin/bash

set -e

BASE=$(dirname "$0")
. $(dirname "$BASE")/common.sh

# Use a fixed sort order.
export LC_ALL=C
#comm -13 --check-order <(dpkg -l | awk '/^ii/ {print $2}' | cut -f1 -d: | sort -u) env/debian/pkgs.txt
for e in $(cat env/debian/pkgs.txt); do apk info ${e}; done | grep description | grep -v bridge | cut -d " " -f 1 | cut -d "-" -f 1
